[db]
major_version = 15

[functions.send-sms]
verify_jwt = false

[functions.paytr-token]
verify_jwt = false

[functions.paytr-webhook]
verify_jwt = false

[functions.provision-auth-user]
verify_jwt = false
